baseURL = "https://puntoproyecto.netlify.app/"
title = "punto proyecto"
author = "cielito networks"
languageCode = "es"
DefaultContentLanguage = "es"
enableInlineShortcodes = true
theme = "tella"
enableRobotsTXT = true

# Please enable this feature if the site is available in Japanese, Chinese or Korean.
#hasCJKLanguage = true

# If you're using Google Analytics, you can enable this feature.
#googleAnalytics = "UA-12345678-1"

# Disqus Comment System
#disqusShortname = ""

[params]

  showBlog = true
  mainSections = ['servicios', 'proyectos']

  googleFonts = true

  [params.logo]
    main = "img/logo/logo.png"
    alt = "Punto Proyecto Logo"

    # The size parameter is the class name of tailwindcss
    # https://tailwindcss.com/
    size = "h-14"

  [params.site]
    name = "Punto Proyecto"

  [params.icon]
    #If you want to use FontAwesome, set this parameter to true.
    fontawesome = true

  [params.homepage_meta_tags]
    meta_description = "Arquitrectura para disfrutar"
    meta_og_title = "Punto proyecto - Arquitectura para exteriores"
    meta_og_type = "website"
    meta_og_url = "https://puntoproyecto.netlify.app/"
    meta_og_image = "https://raw.githubusercontent.com/opera7133/tella/master/images/tn.png"
    meta_og_description = "Punto proyecto - Arquitectura para exteriores"
    meta_twitter_card = "summary_large_image"
    meta_twitter_site = "@username"
    meta_twitter_creator = "@username"

[menu]

 [[menu.main]]
 identifier = "servicios"
 name = "Servicios"
    url = "/servicios/"
    weight = 1

  [[menu.main]]
    identifier = "proyectos"
    name = "Proyectos"
    url = "/proyectos/"
    weight = 2

  [[menu.main]]
    identifier = "somos"
    name = "Somos"
    url = "/somos/"
    weight = 3

  [[menu.main]]
    identifier = "contact"
    name = "Contacto"
    url = "/contact/"
    weight = 3

  # Footer Menu
  [[menu.footer]]
    name = "Home"
    url = "/"
      weight = 1

[[menu.footer]]
  name = "Facebook"
  url = "https://www.facebook.com/p/Punto-Proyecto-100071324896119/"
  pre = "<i class='icon-facebook text-2xl'></i>"
  weight = 2

[[menu.footer]]
  name = "Instagram"
  url = "https://www.instagram.com/punto_proyecto/"
  pre = "<i class='fab fa-instagram text-2xl'></i>"
  weight = 3

[[menu.footer]]
  name = "Correo"
  url = "mailto:info@puntoproyecto.com.ar"
  pre = "<i class='fas fa-envelope text-2xl'></i>"
  weight = 4